### ISSUE TITLE
readme instructions

### ISSUE THREAD

**Issue by pglevy** [Bixal/site-nav-test-drive#4]

**Comment by kbchumley** [comment]
@pglevy  I tested everything and all went well - no issues to report back.

**Comment by pglevy** [comment]
> @pglevy  I tested everything and all went well - no issues to report back. 

Ok, thanks

**Comment by pglevy** [comment]
After Andrew began testing Friday, I realized many government sites may have server security settings that prevent this from working.

I'm going to add an alert to the readme for now, and we can figure out some options moving forward.

**Comment by kbchumley** [comment]
The particular site I tested didn’t have those security settings but I just tested 18f and they have those settings you mentioned

**Comment by pglevy** [comment]
Added caveats for CORS restrictions
